################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "D:/university/studies/FPGA/PJ_FPGA/GA_Genetic_algorithm/GA/GA.xpr"
set rc [catch {
  source -notrace "C:/Users/Alireza/AppData/Roaming/Xilinx/Vivado/ource add_all_waves.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"C:/Users/Alireza/AppData/Roaming/Xilinx/Vivado/ource add_all_waves.tcl\""
}
close_project
